home:
    path: /
    controller: App\Controller\HomeController::index

teams:
    path: /teams
    controller: App\Controller\TeamController::index
    methods: GET

coaches:
    path: /coaches
    controller: App\Controller\CoachController::index

players:
    path: /players
    controller: App\Controller\PlayerController::index