home:
    path: /
    controller: App\Controller\HomeController::index

teams:
    path: /teams
    controller: App\Controller\TeamController::index

team_list:
    path: /teams/list
    controller: App\Controller\TeamController::list
    methods: [GET]

team_show:
    path: /teams/{id}
    controller: App\Controller\TeamController::show
    methods: [GET]

team_redirect:
    path: /teams/redirect
    controller: App\Controller\TeamController::redirectTo

team_create:
    path: /teams/create
    controller: App\Controller\TeamController::create
    methods: [POST]

team_update:
    path: /teams/{id}/update
    controller: App\Controller\TeamController::update
    methods: [POST]

team_delete:
    path: /teams/{id}/delete
    controller: App\Controller\TeamController::delete
    methods: [POST] [DELETE]

coaches:
    path: /coaches
    controller: App\Controller\CoachController::index

coaches_list:
    path: /coaches/list
    controller: App\Controller\CoachController::list
    methods: [GET]

coach_show:
    path: /coaches/{id}
    controller: App\Controller\CoachController::show
    methods: [GET]

coach_redirect:
    path: /coaches/redirect
    controller: App\Controller\CoachController::redirectTo

coach_create:
    path: /coaches/create
    controller: App\Controller\CoachController::create
    methods: [POST]

coach_assign:
    path: /coaches/{id}/assign-club
    controller: App\Controller\CoachController::assignToClub
    methods: [POST] [PUT]

coach_remove:
    path: /coaches/{id}/remove-club
    controller: App\Controller\CoachController::removeFromClub
    methods: [POST] [PUT]

coach_update:
    path: /coaches/{id}/update
    controller: App\Controller\CoachController::update
    methods: [POST]

coach_delete:
    path: /coaches/{id}/delete
    controller: App\Controller\CoachController::delete
    methods: [POST] [DELETE]

players:
    path: /players
    controller: App\Controller\PlayerController::index

players_list:
    path: /players/list
    controller: App\Controller\PlayerController::list
    methods: [GET]

player_show:
    path: /players/{id}
    controller: App\Controller\PlayerController::show
    methods: [GET]

players_redirect:
    path: /players/redirect
    controller: App\Controller\PlayerController::redirectTo

players_create:
    path: /players
    controller: App\Controller\PlayerController::create
    methods: [POST]

players_assign:
    path: /players/{id}/assign-club
    controller: App\Controller\PlayerController::assignToClub
    methods: [PUT]

players_remove:
    path: /players/{id}/remove-club
    controller: App\Controller\PlayerController::removeFromClub
    methods: [PUT]

players_update:
    path: /players/{id}/update
    controller: App\Controller\PlayerController::update
    methods: [PUT]

players_delete:
    path: /players/{id}/delete
    controller: App\Controller\PlayerController::delete
    methods: [DELETE]