home:
    path: /
    controller: App\Controller\HomeController::index

teams:
    path: /teams
    controller: App\Controller\TeamController::index

team_list:
    path: /teams/list
    controller: App\Controller\TeamController::list
    methods: [GET]

coaches:
    path: /coaches
    controller: App\Controller\CoachController::index

players:
    path: /players
    controller: App\Controller\PlayerController::index